name: deploy cloud security
on: workflow_dispatch

env:
  DOTNET_VERSION: '6.0.x'
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  PULUMI_STACK_NAME: incepted/secops
  PULUMI_WORKING_DIRECTORY: infra/iac/Incepted.Infra.SecOps 

jobs:
  deploy-kv:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      
      - name: checkout
        uses: actions/checkout@v3
      - name: setup libraries
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      - name: apply infra update
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: ${{ env.PULUMI_STACK_NAME }}/prod
          work-dir: ${{ env.PULUMI_WORKING_DIRECTORY }}
      